### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by 2044-space-elevator** [HuangYiming0608/China-Crime-Foundation#3]
README 里只有一篇吐槽中国腐败组织的文章。但README的主要作用是诠释该项目的作用、使用方法。
按照文件分布以及全部使用 c# 书写代码来看，应该是一些应用程序？然而没有可以直接使用的发行版……

**Comment by HuangYiming0608** [comment]
你好！
感谢您的反馈！
![发行版地址](https://github.com/HuangYiming0608/China-Crime-Foundation/releases)
README中的文档是程序的文案，您说的作用，使用方法将会在稍后加入！
再吃向您致以崇高的的敬意！

项目负责人
黄奕铭

**Comment by HuangYiming0608** [comment]
如果您有更多问题，请提交新的Issue，这个Issue终结
